### ISSUE TITLE
Prune useless requirements (with python-newspaper).

### ISSUE THREAD

**Issue by alexgerstein** [alexgerstein/Sourcemash#105]
Travis is slow because it needs to install a lot of stuff. Can we start deleting stuff we don't need soon?

**Comment by swglad** [comment]
https://github.com/codelucas/newspaper

**Comment by swglad** [comment]
>>> for a in category_articles:
...     a.download()
...     a.parse()
...     a.publish_date
...

**Comment by swglad** [comment]
```
s = newspaper.build('http://thenextweb.com', memoize_articles=False)
category_articles = s.categories_to_articles()
```

**Comment by alexgerstein** [comment]
We need to memoize articles since they don't get returned in chronological order. If we were to memoize, we'd need to parse and download every article to get the dates.

Instead of using build, we should write out the steps for every part of build _up until_ generate_articles(). This will allow categories_to_articles() to only retrieve the new items.

**Comment by swglad** [comment]
```
feed = newspaper.build(URL)
category_subfeeds = feed.categories
for each category:
   overwrite feed.categories with just one category
   call feed.categories_to_articles()
   create a new feed for each subcategory/subfeed

**Comment by swglad** [comment]
Try using BeautifulSoup to find_all images. Select the first image that contains "logo"

**Comment by swglad** [comment]
### CONCLUSION 

Newspaper does a lot of really interesting things, but the fact that it "merges" all sub-feeds of a single source (e.g. subscribing to "CNN" subscribes you to "CNN Money" + "CNN Science" + "CNN Tech"...) makes it not manageable to be used in our system in it's current form. 

It also lacks feed-level information (e.g. there is no way to extract "title" from newspaper.Source("http://cnn.com") and get CNN; no logo image).

Perhaps we'll want to integrate it later, but for now, we'll leave it aside and say :(
