### ISSUE TITLE
Upvote/Downvote for articles (Backend)

### ISSUE THREAD

**Issue by swglad** [alexgerstein/Sourcemash#75]
API: 
- 'PUT' request on feed-item (api/feeds/'<id>'/items/'<id>') for upvote/downvote

DB: 
1. 'items' table needs a new column "totalVotes"
2. 'votes' (named: user-item) table with user_id-item_id-VoteUp(True if +1, False if -1)
-----> Resolves Issue of keeping track of whether a user has already voted, by doing a lookup to this table
-----> Also allows a "filter by upvote" feature on front-end where we can return all articles that they've upvoted. Similar to "Starred"/"Pinned"/"Favorited"/etc.
------> Helps keep track of unread articles if we add an extra boolean column Unread later

**Comment by alexgerstein** [comment]
Because we need to track unread and starred/votes, do we want to rethink how we organize the database to track voting?

**Comment by alexgerstein** [comment]
Let's make this 'starred' instead of upvote/downvote.

**Comment by swglad** [comment]
No.
