### ISSUE TITLE
Convert front-end to start using Backbone.js

### ISSUE THREAD

**Issue by alexgerstein** [alexgerstein/Sourcemash#8]
For a good explanation of backbone, first read the introduction in their docs and then look at the classic Todo example, http://backbonejs.org/docs/todos.html.

For a good example of how to organize backbone files, see https://github.com/kevinbeaty/flask-todomvc. The tutorial covers all of the API work that we've done, so you don't need to read the steps. This is more for folder organization later on.

This will make things much easier on the front-end.

**Comment by swglad** [comment]
Next steps:
1. Refactor into: models, collections, views
1.2: Add "js/..." to assets.py or else nothing will work.
2. Do the same thing for feed-items
