### ISSUE TITLE
Voting (Frontend)

### ISSUE THREAD

**Issue by alexgerstein** [alexgerstein/Sourcemash#84]
1. Modify feed.tpl to have a button for voting for each item.
2. Once you have the button you can add an event to FeedView that tracks a click event and calls some function in the view that performs a ‘set’ on the collection’s model with the updated property.
- it might be helpful to extract the item to it’s own view. That way you won’t need to track id on the object
if you don’t want to do that, you need to add id=“item-{id}” to the loop
So then on a click event, you use the id to get the right item model out of the collection
(i.e. collection.get(id).set({voted: ‘true’}))

See https://github.com/sameng/NewsReader/tree/82a04231868243daa12b401c84def8a27aa40efa/app/assets

**Comment by swglad** [comment]
Requires #115 to be done first
