### ISSUE TITLE
Visualize categories: items filtered by category view

### ISSUE THREAD

**Issue by swglad** [alexgerstein/Sourcemash#92]
Displays all items filtered by category

Flask REST-ful: make /categories on flask restful to return all categories.

Backbone: create a CategoriesView that just lists the categories that get retrieved from /categories (similar to FeedsView). Then, you need to make categoryView

**Comment by alexgerstein** [comment]
I need this before I can do #74, so can you please work on this first?

**Comment by swglad** [comment]
Display "Sorry, no items in this category" if it's empty.
