### ISSUE TITLE
Fix DB migrations so that we don't need to drop tables each time...

### ISSUE THREAD

**Issue by alexgerstein** [alexgerstein/Sourcemash#93]
We should not need to drop all tables to add a new column. This is silly and defeats the purpose of database versioning. It is also the key barrier to opening the app for Alpha testers. We can't tell them to use a product that will delete all of their data every week...

**Comment by alexgerstein** [comment]
I think our old db_create, db_migrate, db_upgrade files might not have had this issue.

We can test by doing the following on a feature branch:

1) Remove your database.
2) Uninstall flask-migrate.
3) Bring back the old db_create.py, db_migrate.py, etc.
4) Run db_create.py, then db_migrate.py, then db_upgrade.py.
5) Make a small change to an existing table (i.e. add first_name, last_name columns to User.)
6) Run db_migrate.py. Run db_upgrade.py.

If this succeeds, we can then change our manage.py files to use these scripts instead.

**Comment by swglad** [comment]
Use #141 as the "small column change" for step 5 above.

**Comment by alexgerstein** [comment]
ACTUALLY, let's try just setting up Postgres, this is the better approach regardless of the old db files working.

It looks trivial to set up a local postgres db. See here: http://postgresapp.com/documentation/configuration-python.html

**Comment by alexgerstein** [comment]
Since this might get too complicated with postgres, we might as well give the original migration files a shot first.

**Comment by swglad** [comment]
Janky solution 1:

Currently encountering the problem listed here: https://code.google.com/p/sqlalchemy-migrate/issues/detail?id=95. 

I've solved it by using the solution they propose on the bottom which requires you manually overwriting the migration files with a better line of code.

Advantages: allows us to make migrations without trashing the database!
Drawbacks: manually fixing the migration files every time.

Thoughts @alexgerstein?

**Comment by swglad** [comment]
GOT IT!

Change line 575 in flask/lib/python2.7/migrate/changeset/schema.py to:
```stmt = self.table.update().values({self: engine._execute_default(self.default)})```

I'm asking you to do this since flask/ isn't source controlled.

**Comment by swglad** [comment]
Question: will this cause issues for travis and heroku though? @alexgerstein 

If so, this is not a solution...

**Comment by swglad** [comment]
## I've officially figured out what's going on.
Ignore my 3 posts above. 

The current state of migrations actually does work correctly for column additions/deletions except for one big issue: it cannot handle column additions if there is a default value. If you check out that issue link I posted above and look at the if statement that the change falls under, it's checking for a non-None default value and that's where this fails. Clearly sqlalchemy-migrate is still under development and they haven't knocked out all of the kinks yet.

SO, we have 2 solutions:
1. Make the change I said above. This will require patching sqlalchemy-migrate with the fix I listed above, but will allow us to include default values when doing migrations.
2. Keep everything the same EXCEPT never do a migration where a column requires a default value. If we want it to have a default value, we should insert it ourselves when creating the new item.

Thoughts? Sorry for all the spam....

**Comment by alexgerstein** [comment]
Why doesn't sqlalchemy-migrate make that line change in their source code if it's such a simple fix?

Also, will required fields work?

**Comment by swglad** [comment]
1. That code block has had ```#TODO``` on it and has remained unchanged since 2011. I'm not sure why it hasn't been fixed or whether that fix ended up causing other issues that they didn't/couldn't deal with.

**Comment by swglad** [comment]
2. What do you mean by "required"? I can't find any indication of that in the various ```models.py``` or migration files.

If we need a column to have a value, then we *must* set it ourselves when we initially add the entry to the database since we can't do default values.

**Comment by alexgerstein** [comment]
Right. But I was wondering if we can make a column required, but without a default value, so we'll at least get an error if we try adding an item that's missing a value.

**Comment by swglad** [comment]
Where do we set columns as required? I don't see any examples of that in our code

**Comment by swglad** [comment]
Ah, you mean like make a column with ```Nullable=False```.  Currently, our only examples of that are primary keys and foreign keys, so I'm not sure what situation it'll be strictly necessary to do that. It just seems that the onus will be on us to maintain the data like we want it - not perfect, but it's not the worst possible outcome.

**Comment by swglad** [comment]
And until we have beta users, we can always make a column with a default and just delete the entire database and do another db init....lol

**Comment by alexgerstein** [comment]
That kind of defeats the purpose of this issue haha.

The issue with not having some way for the db to check Null is that when we have code to sum/count/average column values, we'll need to add messy check for null values. I was hoping we could add some measures to avoid this clutter.

**Comment by swglad** [comment]
I know, I know. 

Well both the old migration files and alembic fail at adding new columns with default values. So if we take that as given, what's the next step?

**Comment by alexgerstein** [comment]
Does it fail at adding nullable=False?

-- 
Alex Gerstein
gerstein.alex@gmail.com

On March 26, 2015 at 3:51:58 PM, Scott Gladstone (notifications@github.com) wrote:

I know, I know.

Well both the old migration files and alembic fail at adding new columns with default values. So if we take that as given, what's the next step?

**Comment by swglad** [comment]
[And here's the commit where we switched from the old migration files to Flask-migrate] (https://github.com/alexgerstein/Sourcemash/commit/ebe42e7479f8e26f07ba75aea4e1e64636bee14d#diff-0d43678dcd474a81666b4dfb9bb4d2f7)

**Comment by swglad** [comment]
Alembic seems to have fixed itself for now (perhaps due to a sqlalchemy/sqlalchemy-migrate upgrade). Closing for now.
